MKDIRS := $(MKDIRS) $(LIB_DIR)

LIBTAR := $(LIB_DIR)/$(LIBTAR)

$(LIBTAR) : | $(LIB_DIR)


$(LIBTAR) : ARCHIVE_OBJECTS := $(LIB_O) $(LIB_INIT_O)
$(LIBTAR) : $(LIB_O) $(LIB_INIT_O)
	$(AR) $@ $(ARCHIVE_OBJECTS)

all : $(LIBTAR)
